---
title: "Data_exploration"
author: "Elena Shaw"
date: "07/07/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(mice)

data = read.csv('data_raw/RawData_unlocked.csv')

# trace(psych::polychoric, edit=TRUE)
```

```{r}
data_clean = data %>%
              select(-c("bilec_home_output","bilec_english_output","bilec_total_output",
                        "bilec_home_input","bilec_english_input")) %>%
              mutate(pvt_mean_rt = as.numeric(as.character(pvt_mean_rt)),
                     wasi_sum_rawscores = na_if(wasi_sum_rawscores, 0)) %>%
              mutate_if(is.numeric, list(~na_if(., 888)))

factor_binary = c(0,1)
factor_20_dec = c(seq(0,20, by=.1),NA)

data_numeric = data_clean %>%
                mutate(bilec_total_input = bilec_total_input/100,
                       flanker_percenterrors_congruent = flanker_percenterrors_congruent/100,
                       flanker_percenterrors_incongruent = flanker_percenterrors_incongruent/100,
                       pvt_mean_lapse_rt = ifelse(pvt_number_of_lapses==0, 0, pvt_mean_lapse_rt)
                       )
# write.csv(data_numeric,'data/data_num.csv', row.names=F)

data_factor = data_clean %>%
              mutate(part_no = as.factor(part_no),
                     gender = factor(gender, levels=factor_binary),
                     age_m = factor(age_m, levels=c(seq(70,162),NA)),
                     diagnosis = factor(diagnosis, levels=factor_binary),
                     SCQ = factor(SCQ, levels=c(seq(0,39),NA)),
                     bpvs_raw = factor(bpvs_raw, levels=c(seq(0,155),NA)),
                     wasi_sum_rawscores = na_if(wasi_sum_rawscores, 0),
                     wasi_sum_rawscores = factor(wasi_sum_rawscores, levels=c(seq(1,100),NA)),
                     tomi_early = factor(tomi_early, levels=factor_20_dec),
                     tomi_basic = factor(tomi_basic, levels=factor_20_dec),
                     tomi_advanced = factor(tomi_advanced, levels=factor_20_dec),
                     tomi_tb_totalscore = factor(tom_tb_totalscore, levels = c(seq(0,15),NA)),
                     bilec_total_input = bilec_total_input/100,
                     age_acquisition = factor(age_acquisition, levels=c(seq(0,5),NA)),
                     where_english = factor(where_english, levels=c(seq(1,4),NA)),
                     brief_raw_inhibit = factor(brief_raw_inhibit, 
                                                levels=c(seq(7,27),NA)),
                     brief_raw_self.monitor = factor(brief_raw_self.monitor,
                                                      levels=c(seq(4,16),NA)),
                     brief_raw_shift = factor(brief_raw_shift,
                                              levels=c(seq(8,24),NA)),
                     brief_raw_emotional_control = factor(brief_raw_emotional_control,
                                                          levels=c(seq(8,24),NA)),
                     brief_raw_initiate = factor(brief_raw_initiate,
                                                 levels=c(seq(5,22),NA)),
                     brief_raw_working_memory = factor(brief_raw_working_memory,
                                                       levels=c(seq(7,24),NA)),
                     brief_raw_plan_organise = factor(brief_raw_plan_organise,
                                                      levels=c(seq(8,24),NA)),
                     brief_raw_task_monitor = factor(brief_raw_task_monitor,
                                                     levels=c(seq(5,15),NA)),
                     brief_raw_organisation_of_materials = factor( 
                                          brief_raw_organisation_of_materials,
                                          levels=c(seq(6,18),NA)),
                     flanker_percenterrors_congruent = flanker_percenterrors_congruent/100,
                     flanker_percenterrors_incongruent = flanker_percenterrors_incongruent/100,
                     pvt_mean_lapse_rt = ifelse(pvt_number_of_lapses==0, 0, pvt_mean_lapse_rt),
                     pvt_number_of_lapses = factor(pvt_number_of_lapses, levels=c(seq(0,40),NA)),
                     pvt_count_falsestarts = factor(pvt_count_falsestarts)
                     )

# summary of nan's
data_factor %>%
  summarise_all(funs(sum(is.na(.)))) %>%
  select(contains("pvt"))

data_numeric %>%
  summarise_all(funs(sum(is.na(.)))) %>%
  select(contains("pvt"))

# saveRDS(data_factor, file='data/data_fact.RDS')

# ASD_data = data_clean %>% filter(diagnosis == 1)
# TD_data = data_clean %>% filter(diagnosis == 0)
# 
# ASD_F_data = data_clean %>% filter(diagnosis == 1, gender == 1) # 16
# ASD_M_data = data_clean %>% filter(diagnosis == 1, gender == 0) # 22
# TD_F_data = data_clean %>% filter(diagnosis == 0, gender == 1) # 21
# TD_M_data  = data_clean %>% filter(diagnosis == 0, gender == 0) # 30
```
# EF data screening
```{r}
EF_numeric = data_numeric %>% select(c(contains(c("brief","flanker","pvt"))),part_no)
EF_factor = data_factor %>% select(c(contains(c("brief","flanker","pvt"))),part_no)

EF_numeric_cln = EF_numeric %>%
                  mutate(brief_raw_self.monitor = 
                           replace(brief_raw_self.monitor, 
                                   brief_raw_self.monitor == 48,
                                   NA))
EF_factor_cln = EF_factor %>%
                  mutate(brief_raw_self.monitor = 
                           replace(brief_raw_self.monitor, 
                                   brief_raw_self.monitor == 48,
                                   NA))
```
```{r}
brief_complete = EF_numeric_cln %>% 
                  select(c(contains(c("brief"))),part_no) %>% 
                  na.omit()
# ggplot(tidyr::gather(brief_complete), aes(value)) + 
#     geom_histogram(bins = 10) + 
#     facet_wrap(~key, scales = 'free_x')
# GGally::ggpairs(brief_complete %>% select(-part_no), progress = F)

flanker_complete = EF_numeric_cln %>% 
                    select(c(contains(c("flanker"))),part_no) %>% 
                    na.omit()
# ggplot(tidyr::gather(flanker_complete), aes(value)) + 
#     geom_histogram(bins = 10) + 
#     facet_wrap(~key, scales = 'free_x')
# GGally::ggpairs(flanker_complete %>% select(-part_no), progress = F)

pvt_complete = EF_numeric_cln %>% 
                select(c(contains(c("pvt"))),part_no) %>% 
                na.omit()
# ggplot(tidyr::gather(pvt_complete), aes(value)) + 
#     geom_histogram(bins = 10) + 
#     facet_wrap(~key, scales = 'free_x')
# GGally::ggpairs(pvt_complete %>% select(-part_no),progress = F)

GGally::ggpairs(brief_complete %>% select(-part_no), progress = F)
GGally::ggpairs(flanker_complete %>% select(-part_no), progress = F)
GGally::ggpairs(pvt_complete %>% select(-part_no),progress = F)
```

### Will taking log of error % help?
```{r}
flanker_ln = flanker_complete %>%
              mutate(ln_congruent = log(flanker_percenterrors_congruent),
                     ln_incongruent = log(flanker_percenterrors_incongruent),
                     .keep = "unused"
                     )
GGally::ggpairs(flanker_ln %>% select(-part_no), progress = F)
```
### Remove pvt_count_falsestarts?
```{r}
brief_complete$brief_comb = brief_complete %>%
                              select(-part_no) %>%
                              apply(1, sum, na.rm=TRUE)

falsestart1 = EF_numeric_cln %>% 
                  select(c(contains(c("brief"))),part_no,pvt_count_falsestarts) %>% 
                  na.omit()
falsestart2 = EF_numeric_cln %>% 
                  select(c(contains(c("flanker"))),part_no,pvt_count_falsestarts) %>% 
                  na.omit()

# ggplot(tidyr::gather(EF_comb), aes(value)) + 
#     geom_histogram(bins = 10) + 
#     facet_wrap(~key, scales = 'free_x')
# GGally::ggpairs(EF_comb  %>% select(-part_no),progress = F)


GGally::ggpairs(falsestart1 %>% select(-part_no), progress = F)
GGally::ggpairs(falsestart2 %>% select(-part_no), progress = F)
```
### Combine all
```{r}
EF_complete_comb = EF_numeric_cln %>% 
                  na.omit() %>%
                  select(-c(contains("brief"), pvt_count_falsestarts))
EF_complete_comb$brief_sum = EF_numeric_cln %>% 
                          na.omit() %>%
                          select(contains(c("brief"))) %>%
                          apply(1, sum, na.rm=TRUE)

GGally::ggpairs(EF_complete_comb %>% select(-part_no),progress = F)
```
## Ramsey RESET test
```{r}
EF_complete = EF_numeric_cln %>% na.omit() %>% select(-part_no)

sig10_cols = as.data.frame(matrix(0, ncol = 2, nrow = 306))
sig5_cols = as.data.frame(matrix(0, ncol = 2, nrow = 306))
i=0
for (i in 1:ncol(EF_complete)){
  for (j in 2:ncol(EF_complete)) {
    col1 = names(EF_complete)[i]
    col2 = names(EF_complete)[j]
    if (col1 != col2) {
      pval = lmtest::resettest(EF_complete[,i] ~ EF_complete[,j],
                  power=2,
                  type="regressor")$p.value
      if (pval<.1){
        sig10_cols[i,] = c(col1,col2)
        if(pval<.05){
          sig5_cols[i,] = c(col1,col2)
        }
      }
    }
  }
}

sig10_cols %>% filter(V1>0) %>% arrange(V1,V2)
sig5_cols %>% filter(V1>0) %>% arrange(V1,V2)

sig10_cols %>% group_by(V1) %>% tally()
sig10_cols %>% group_by(V2) %>% tally()
```
```{r}
plot(x=EF_complete$flanker_mean_rt_incongruent, y=EF_complete$pvt_mean_rt)
```

## Check Skew and Kurtosis
```{r}
library(fBasics)
# Skew ≥2 and Kurtosis ≥7 affect Pearson corr.

colSkewness(EF_complete) 
# problem cols: pvt_count_falsestarts, flanker_percenterrors_congruent,
#               pvt_mean_rt, pvt_mean_lapse_rt, pvt_count_falsestarts
colKurtosis(EF_complete)
# problem cols: flanker_percenterrors_congruent, pvt_mean_rt,
#               pvt_mean_lapse_rt
```

## Polychoric/Polyserial corr
```{r}
source("func.R")
ordinal_data = EF_numeric_cln %>% 
                  na.omit() %>%
                  select(c(contains(c("brief")),"pvt_number_of_lapses",
                           "pvt_count_falsestarts"))
  
continuous_data = EF_numeric_cln %>% 
                  na.omit() %>%
                  select(c(contains(c("flanker")),"pvt_mean_rt",
                           "pvt_mean_lapse_rt"))

ordinal_psych_output = psych::polychoric(ordinal_data)
# saveRDS(ordinal_psych_output,'data/EF_ordinal_polycorr.RDS')
ordinal_max_corr = find_max_corr(ordinal_data, ordinal_psych_output$rho)
colnames(ordinal_max_corr$corr) = colnames(ordinal_data)
rownames(ordinal_max_corr$corr) = colnames(ordinal_data)

cont_max_corr = find_max_corr(continuous_data)
rownames(cont_max_corr$corr) = colnames(continuous_data)
colnames(cont_max_corr$corr) = colnames(continuous_data)

comb_psych_output = psych::polyserial(continuous_data,ordinal_data)
cross_max_corr = find_max_corr(EF_numeric_cln %>% na.omit(), comb_psych_output)
rownames(cross_max_corr$corr) = rownames(comb_psych_output)
colnames(cross_max_corr$corr) = colnames(comb_psych_output)

mix_cont_corr = bind_rows(cont_max_corr$corr, cross_max_corr$corr)
mix_ord_corr = bind_cols(ordinal_max_corr$corr,cross_max_corr$corr)
all_EF_corr = bind_rows(as.data.frame(t(mix_cont_corr)),mix_ord_corr)
# write.csv(all_EF_corr,'data/all_EF_correlations.csv')
all_EF_corr = read.csv('data/all_EF_correlations.csv') %>% select(-X)
```

## Missing Data explore
```{r}
non_SC_data = data_numeric %>% select(-contains(c("tom","et_")))

missing_recs = non_SC_data %>% select(-c(SCQ,part_no)) %>% filter_all(any_vars(is.na(.))) %>% select(-contains(c("brief","pvt","flanker")))

mice::md.pattern(non_SC_data)

mis_obj = VIM::aggr(non_SC_data, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))

missing_cols = mis_obj$missings %>% filter(Count >0)
```

## Safe to assume Missing At Random?
```{r}
prop_missing_df = bind_rows(missing_recs %>% mutate(cohort="missing"), data_numeric %>% select(names(missing_recs)) %>% mutate(cohort="original")) 

# org_ct = nrow(data_numeric)
# miss_ct = nrow(missing_recs)
# 
# compare_prop = function(comb_df, col_name) {
#   original = comb_df %>% filter(cohort=="original") %>% 
#               group_by(!!sym(col_name), cohort) %>%
#               summarise(n = n()) %>%
#               mutate(freq = n / org_ct)
#   missing = comb_df %>% filter(cohort=="missing") %>% 
#               group_by(!!sym(col_name), cohort) %>%
#               summarise(n = n()) %>%
#               mutate(freq = n / miss_ct)
#   ggplot(bind_rows(original,missing), aes(x=factor(!!sym(col_name)),y=freq,fill=cohort)) +
#     geom_bar(stat='identity',position = "dodge2")
# }
#   
# for (column in names(missing_recs)) {
#   print(compare_prop(prop_missing_df, column))
# }

for (column in missing_cols$Variable) {
  # print(lattice::histogram(~ gender | is.na(data_numeric[column]), 
  #                          data = data_numeric,
  #                          xlab = paste(column, ' + gender')))
  print(lattice::histogram(~ age_m | is.na(data_numeric[column]),
                           data = data_numeric,
                           xlab = paste(column, ' + age')))
  # print(lattice::histogram(~ diagnosis | is.na(data_numeric[column]),
  #                          data = data_numeric,
  #                          xlab = paste(column, ' + diagnosis')))
}
```

## Multiple Imputation
```{r}
demo_data = data_factor %>% select(part_no, gender, age_m, diagnosis)
EF_MDA = inner_join(demo_data,EF_factor_cln, by='part_no') %>% select(-part_no)

MI_obj = mice::mice(EF_MDA, maxit=0)

# Extract predictorMatrix and methods of imputation 
pred_matrix = MI_obj$predictorMatrix
# pred_matrix[,colnames(EF_factor_cln %>% select(-part_no))]=0
pred_matrix[colnames(demo_data %>% select(-part_no)),]=0

method = MI_obj$method
method[colnames(ordinal_data)] = "polr"

MI_results = mice(EF_MDA, maxit = 5, 
             predictorMatrix = pred_matrix, 
             method = method, print =  FALSE)

# saveRDS(MI_results, file='data/MI_results.RDS')
MI_results = readRDS('data/MI_results.RDS')

# plot(MI_results)
MI_results$imp

all_MI_data = mice::complete(MI_results,action='long',include=F) %>%
                mutate_if(is.factor,as.numeric)
# write.csv(all_MI_data, 'data/MI_complete_data.csv', row.names=F)
# all_MI_data = read.csv('data/MI_complete_data.csv')
```

```{r}
source("func.R")
IM_data1 = all_MI_data %>% filter(.imp==1) %>% select(-c(.imp,.id))
IM_data2 = all_MI_data %>% filter(.imp==2) %>% select(-c(.imp,.id))
IM_data3 = all_MI_data %>% filter(.imp==3) %>% select(-c(.imp,.id))
IM_data4 = all_MI_data %>% filter(.imp==4) %>% select(-c(.imp,.id))
IM_data5 = all_MI_data %>% filter(.imp==5) %>% select(-c(.imp,.id))

data1_max_corr = data_max_corr(IM_data1)
data2_max_corr = data_max_corr(IM_data2)
data3_max_corr = data_max_corr(IM_data3)
data4_max_corr = data_max_corr(IM_data4)
data5_max_corr = data_max_corr(IM_data5)

all_max_corr = bind_rows(data1_max_corr$corr %>% mutate(imp=1),
                      data2_max_corr$corr %>% mutate(imp=2),
                      data3_max_corr$corr %>% mutate(imp=3),
                      data4_max_corr$corr %>% mutate(imp=4),
                      data5_max_corr$corr %>% mutate(imp=5))

# write.csv(all_max_corr, 'data/MI_max_corrs.csv',row.names = F)

CC_corr_mean = colMeans(all_EF_corr)
data1_corr_mean = colMeans(data1_max_corr$corr)
data2_corr_mean = colMeans(data2_max_corr$corr)
data3_corr_mean = colMeans(data3_max_corr$corr)
data4_corr_mean = colMeans(data4_max_corr$corr)
data5_corr_mean = colMeans(data5_max_corr$corr)

rbind(CC_corr_mean,data1_corr_mean,data2_corr_mean,
      data3_corr_mean,data4_corr_mean,data5_corr_mean)
```

## Assume ordinal is continuous, only fix skew/kurtosis
```{r}
source("func.R")
data1_cons_corr = as.data.frame(data_cons_corr(IM_data1))
data2_cons_corr = as.data.frame(data_cons_corr(IM_data2))
data3_cons_corr = as.data.frame(data_cons_corr(IM_data3))
data4_cons_corr = as.data.frame(data_cons_corr(IM_data4))
data5_cons_corr = as.data.frame(data_cons_corr(IM_data5))

all_cons_corr = bind_rows(data1_cons_corr %>% mutate(imp=1),
                      data2_cons_corr %>% mutate(imp=2),
                      data3_cons_corr %>% mutate(imp=3),
                      data4_cons_corr %>% mutate(imp=4),
                      data5_cons_corr %>% mutate(imp=5))

# write.csv(all_cons_corr, 'data/MI_cons_corrs.csv',row.names = F)
```
